feat(adapters): add gene_ontology adapter, change weave.py + CGI last version
oncodash/oncodashkb pull request #8
Opened 2024-06-04 13:27 UTC by kgaydukova

2024-06-06 09:06 UTC, jdreo requested changes
Impressive work!

I only added minor comments, and I would like to have the ontology parsing using a bullet-proof module rather than parsing by hand.

I think we are also missing README files for each adapters, that would explain the global rationale of how the data source is handled (especially here, since we have an ad-hoc code instead of a simple declarative mapping).

2024-06-06 09:06 UTC, jdreo commented on config/schema_config.yaml
> +    is_a: molecular activity #name in biolink
I am surprised we need to do that. Wouldn’t BioCypher be supposed to handle the inheritance by itself, since we specified the join node? Isn’t it the case for `biological process`?

2024-06-06 09:06 UTC, jdreo commented on config/schema_config.yaml
> +    is_a: macromolecular machine to molecular activity association #  edge type from biolink
Just to be sure to understand correctly: does GO have a hierarchy of edge types or just single edge types?

2024-06-11 14:39 UTC, jdreo requested changes
Looks good in general, only two minor comments remaining!

2024-06-11 14:39 UTC, jdreo commented on oncodashkb/adapters/README.md
This is a very good description of the high-level interface. I think it should actually go into the root README.

2024-06-11 14:39 UTC, jdreo commented on weave.py
> +    parser.add_argument("-g_genes", "--gene_ontology_genes", metavar="TXT", action="append",
Options starting with a single dash should be one letter long. I suggest using `-g` and `-G`.

2024-06-11 14:39 UTC, jdreo commented on oncodashkb/adapters/README.md
For the README in the adapter directory, I think it would make sense to have explanations as to *why* you did the mapping this way. Things like the choice of such or such column, why and how you defined the mapping of types from column values (instead of the column name itself), etc.

2024-06-13 14:07 UTC, kgaydukova commented on oncodashkb/adapters/README.md
Done

2024-06-13 14:07 UTC, kgaydukova commented on weave.py
> +    parser.add_argument("-g_genes", "--gene_ontology_genes", metavar="TXT", action="append",
Done

2024-09-11 11:29 UTC, merged